# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"*\n\x08\x46ileData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"!\n\x0eUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x0f\x44ownloadRequest\x12\x14\n\x0c\x66ileLocation\x18\x01 \x01(\t\" \n\x10\x44ownloadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"%\n\rDeleteRequest\x12\x14\n\x0c\x66ileLocation\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9c\x01\n\x0c\x46ileTransfer\x12(\n\nUploadFile\x12\t.FileData\x1a\x0f.UploadResponse\x12\x33\n\x0c\x44ownloadFile\x12\x10.DownloadRequest\x1a\x11.DownloadResponse\x12-\n\nDeleteFile\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEDATA']._serialized_start=14
  _globals['_FILEDATA']._serialized_end=56
  _globals['_UPLOADRESPONSE']._serialized_start=58
  _globals['_UPLOADRESPONSE']._serialized_end=91
  _globals['_DOWNLOADREQUEST']._serialized_start=93
  _globals['_DOWNLOADREQUEST']._serialized_end=132
  _globals['_DOWNLOADRESPONSE']._serialized_start=134
  _globals['_DOWNLOADRESPONSE']._serialized_end=166
  _globals['_DELETEREQUEST']._serialized_start=168
  _globals['_DELETEREQUEST']._serialized_end=205
  _globals['_DELETERESPONSE']._serialized_start=207
  _globals['_DELETERESPONSE']._serialized_end=240
  _globals['_FILETRANSFER']._serialized_start=243
  _globals['_FILETRANSFER']._serialized_end=399
# @@protoc_insertion_point(module_scope)
